// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo1bIVAezZ4pX73BAMOXpY6HxZMQKBQRA',
    appId: '1:326786636052:web:e7294ac496e6aafbf8ca01',
    messagingSenderId: '326786636052',
    projectId: 'flutterproject-d3e0b',
    authDomain: 'flutterproject-d3e0b.firebaseapp.com',
    storageBucket: 'flutterproject-d3e0b.appspot.com',
    measurementId: 'G-2C0WMT5LF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmiOuP9eeqTU3HYLtB5SZhynKqKx4Pu-A',
    appId: '1:326786636052:android:c213fd53d62d5bebf8ca01',
    messagingSenderId: '326786636052',
    projectId: 'flutterproject-d3e0b',
    storageBucket: 'flutterproject-d3e0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAjNY1X-CrQ1MCgR2gIn9pgRLfRdrPQ_8',
    appId: '1:326786636052:ios:99054f4264d6e7baf8ca01',
    messagingSenderId: '326786636052',
    projectId: 'flutterproject-d3e0b',
    storageBucket: 'flutterproject-d3e0b.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );
}
